package org.quest;

public enum ActionType {
    START_GAME,
    PLAY_CARD,
    DRAW_QUEST_CARD,
    PLAGUE,
    QUEENS_FAVOR,
    PROSPERITY,
    TRIM_CARD,
    START_QUEST,
    SPONSOR_QUEST,
    ADD_CARD_TO_STAGE,
    QUIT_STAGE_SETUP,
    START_QUEST_ATTACK,
    PARTICIPATE_IN_QUEST,
    ADD_CARD_TO_ATTACK,
    QUIT_ATTACK_SETUP,
    RESOLVE_ATTACKS,
    END_QUEST,
    CLEANUP_QUEST,
    NEXT_TURN,
    END_GAME
}
