package org.quest;

public enum Response {
    SUCCESS,
    NO_QUEST_STARTED,
    QUEST_COMPLETED,
    QUEST_NOT_COMPLETED,
    QUEST_ALREADY_COMPLETED,
    NO_CARDS_IN_STAGE,
    ALL_STAGES_SET,
    INSUFFICIENT_STAGE_VALUE,
    NOT_IN_HAND,
    MULTIPLE_FOES,
    NO_FOES_IN_ATTACK,
    REPEATED_WEAPON,
    TRIM_REQUIRED,
    NO_TRIM_REQUIRED,
    PLAYER_NOT_IN_QUEST,
    CARD_ALREADY_DRAWN,
    NO_WINNERS,
    WINNERS,
    INVALID_INPUT,
    NO_CARD_DRAWN,
    INVALID_REQUEST
}
